apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: flask-health-api-template
  annotations:
    scenarios.ai.sap.com/description: "Flask Health API"
    scenarios.ai.sap.com/name: "flask-health-scenario"
    executables.ai.sap.com/description: "Health check API"
    executables.ai.sap.com/name: "flask-health-executable"
  labels:
    scenarios.ai.sap.com/id: "flask-health-scenario"
    ai.sap.com/version: "1.0.0"
spec:
  inputs:
    parameters: []
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: "{}"
      labels: "{\"ai.sap.com/resourcePlan\": \"starter\"}"
    spec: |
      predictor:
        minReplicas: 1
        maxReplicas: 2
        containers:
          - name: kserve-container
            image: jerushan/transaction-analyzer-rnd:latest
            ports:
              - containerPort: 8080
                protocol: TCP
            command: ["gunicorn"]
            args:
              - "--bind"
              - "0.0.0.0:8080"
              - "app:app"
