apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: transanalyzerptm-serving
  annotations:
    scenarios.ai.sap.com/description: "transanalyzerpt Serving Template"
    scenarios.ai.sap.com/name: "transanalyzerptm"
    executables.ai.sap.com/description: "Serve transanalyzerpt model predictions"
    executables.ai.sap.com/name: "transanalyzerptm-serving"
  labels:
    scenarios.ai.sap.com/id: "transanalyzerptm"
    ai.sap.com/version: "1.0.0"
spec:
  inputs:
    artifacts:
      - name: trainedmodels
      - name: trainedmodelsnew
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: "{}"
      labels: "{\"ai.sap.com/resourcePlan\": \"starter\"}"
    spec: |
      predictor:
        minReplicas: 1
        maxReplicas: 2
        volumes:
          - name: models-new-volume
            emptyDir: {}
        initContainers:
          - name: download-model2
            image: amazon/aws-cli:latest
            command: ["sh", "-c"]
            args:
              - |
                aws s3 cp $STORAGE_URI_NEW /mnt/models_new/ --recursive
            env:
              - name: STORAGE_URI_NEW
                value: "{{inputs.artifacts.trainedmodelsnew}}"
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: default
                    key: accessKeyId
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: default
                    key: secretAccessKey
              - name: AWS_DEFAULT_REGION
                value: "ap-southeast-1"
            volumeMounts:
              - name: models-new-volume
                mountPath: /mnt/models_new
        containers:
          - name: kserve-container
            image: docker.io/jerushan/transanalyzer:pred
            ports:
              - containerPort: 8080
                protocol: TCP
            command: ["python"]
            args:
              - "prediction/app.py"
            env:
              - name: STORAGE_URI
                value: "{{inputs.artifacts.trainedmodels}}"
              - name: MODEL_PATH
                value: "/mnt/models"          # ← auto-mounted by AI Core
              - name: MODEL_PATH_NEW
                value: "/mnt/models_new"      # ← mounted via initContainer
            volumeMounts:
              - name: models-new-volume
                mountPath: /mnt/models_new
            resources:
              requests:
                cpu: "0.5"
                memory: "512Mi"
              limits:
                cpu: "1"
                memory: "1Gi"
